# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: '**/*.Tests.csproj'
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: |
      **/*.csproj
      !**/*.Tests.csproj
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish'
    zipAfterPublish: false
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/MagicHome.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)/nuget'
    versioningScheme: 'off'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Release Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
    ArtifactName: 'publish'
    publishLocation: 'Container'
- task: PublishBuildArtifacts@1
  displayName: 'Publish NuGet Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/nuget'
    ArtifactName: 'nuget'
    publishLocation: 'Container'